title: OSI-PIA
description: Public articles and standards for Organizational Systems Intelligence and Professional Identity Architecture.
theme: minima
url: "https://dingus-mcguillacutty.github.io"
baseurl: "/OSI-PIA-clean"

header_pages:
  - publications/articles/index.md